@base_url=http://localhost:3000


#* PROPERTIES
### Get Properties
@limit=2
@offset=2
GET {{base_url}}/properties/simple-pagination?limit={{limit}}&offset={{offset}} HTTP/1.1
Content-Type: application/json

### Get Properties Pretty Pagination
@page=1
@take=10
@order=DESC
GET {{base_url}}/properties?page={{page}}&take={{take}}&order={{order}} HTTP/1.1
Content-Type: application/json


### Get Property by ID
@term=bfc3f6fd-fce4-44ea-a7e4-7955a1cae354
GET {{base_url}}/properties/{{term}} HTTP/1.1
Content-Type: application/json

### Create Property
POST {{base_url}}/properties HTTP/1.1
Content-Type: application/json

{
    "title": "Big House on the Hill7",
    "description": "This is a nice house",
    "price": 1000000,
    "type": "sale",
    "bedrooms": 3,
    "bathrooms": 2,
    "area": 15,
    "garage": true,
    "images": [],
    "status": "active"
}

### Update property
PATCH  {{base_url}}/properties/{{term}} HTTP/1.1
Content-Type: application/json

{
    "description": "This is a nice REALLY house",
    "images": ["www.example1.com"]
}


### Delete Property
DELETE  {{base_url}}/properties/{{term}} HTTP/1.1
Content-Type: application/json
